.TH MOONUNIT "1" "February 2008"
.SH NAME
moonunit \- Runs \fBMoonUnit\fP unit tests in shared libraries
.SH SYNOPSIS
moonunit [\fIoptions\fP] <libraries...>
.SH DESCRIPTION
\fBmoonunit\fR detects, loads and invokes \fBMoonUnit\fR
unit tests in dynamic shared libraries.  By default, test
results are formatted and printed to the console in real
time, but an alternate logging plugins may optionally be
specified.

.SH OPTIONS
\fBmoonunit\fR expects one or more shared libraries
containing unit tests to be specified as arguments. 
.PP
In addition, the following options are available:
.PP
.IP \fB-s\fP\ \fIsuite\fP
Runs tests in suite \fIsuite\fP.  This option may be
specified multiple times to run tests in multiple
suites.
.IP \fB--suite=\fP\fIsuite\fP
Equivalent to \fB-s\fP
.IP \fB-t\fP\ \fIsuite\fP/\fIname\fP
Runs the test named \fIname\fP in suite \fIsuite\fP.  This
option may be specified multiple times to run multiple
different tests.
.IP \fB--test=\fP\fIsuite\fP/\fIname\fP
Equivalent to \fB-t\fP
.IP \fB-a\fP
Run all tests in all suites.  This is the default behavior
if no instances of \fB-s\fP or \fB-t\fP are specified.
.IP \fB--all\fP
Equivalent to \fB-a\fP
.IP \fB-g\fP
Interactively trace failed tests in \fBGDB\fP, the GNU debugger.
Each test that fails will immediately be rerun inside a GDB
session with a breakpoint set at the line or function nearest
to the failure.  After leaving the \fBGDB\fP session, \fBmoonunit\fR
will resume at the next unit test.
.IP \fB--gdb\fP
Equivalent to \fB-g\fP
.IP \fB-l\fP\ \fIname\fP
Attempts to load and use the logger plugin \fIname\fP.
The default logger plugin is "console", which neatly formats
and prints test results to stdout.
.IP \fB--logger=\fP\fIname\fP
Equivalent to \fB-l\fP
.IP \fB-o\fP\ \fIcomponent\fP.\fIoption\fP:\fIvalue\fP
Sets an option for a particular test component, such as
the logger or test runner.  These options are largely
plugin-specific, although most plugins honor a standard
set of common options.

\fIcomponent\fP may be one of "logger" or "runner", with
\fIoption\fP and \fIvalue\fP being the option name and value
to set on the plugin filling that particular role.
.IP \fB-?\fP
Lists brief usage and option information and exits.
.IP \fB--help\fP
Equivalent to \fB-?\fP
.SH EXAMPLES
.TP
moonunit library1.so library2.so

Run all unit tests in library1.so and library2.so, printing
results to the console.
.TP
moonunit -t Foo/bar -g library.so

Run test "bar" in the suite "Foo" in library.so and trace any
failure in \fBGDB\fP.
.TP
moonunit -o logger.ansi:false library.so

Run all tests in library.so, printing results to the console without
ANSI color or fonts codes.
.TP
moonunit -l xml library.so

Run all tests in library.so, printing an XML-formatted test summary
suitable for postprocessing to stdout.
.SH COPYRIGHT
Copyright (c) 2007-2008, Brian Koropoff.  All rights reserved.

Redistribution in source and binary form is permitted under
the terms of the 3-clause BSD license.  See COPYING in the
documentation or source distribution for details.
.SH SEE\ ALSO
\fBmoonunit-lt\fP(1), \fBmoonunit-stub\fP(1), \fBmoonunit-strip\fP(1)
